name: build

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1.0.2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - id: branch-name
        uses: tj-actions/branch-names@v5.2
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: docker-buildx-${{ github.sha }}
          restore-keys: |
            docker-buildx-
      - run: |
          IMAGE_ID=${{ github.repository }}
          IMAGE_ID=${IMAGE_ID,,}
          VERSION=$(echo ${{steps.branch-name.outputs.current_branch}} | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo "image_tag=$IMAGE_ID:$VERSION" >> $GITHUB_ENV
      - uses: docker/build-push-action@v2.1.0
        with:
          file: Dockerfile
          build-args: |
            BuildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          tags: ghcr.io/${{ env.image_tag }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
